version: "3.9"
   
services:
  db:
    image: postgres:13.3-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=etagi_db
      - POSTGRES_USER=etagi_admin
      - POSTGRES_PASSWORD=etagi_passwd
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/etagi
    ports:
      - "8000:8000"
    depends_on:
      - db