# Generated by Django 3.2.5 on 2021-07-21 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('expiration_date', models.DateTimeField(null=True, verbose_name='expiration date')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('priority', models.CharField(choices=[('LW', 'low'), ('MD', 'middle'), ('HI', 'high')], default='LW', max_length=2, verbose_name='priority')),
                ('status', models.CharField(choices=[('TW', 'to work'), ('IP', ' in progress'), ('FD', 'finished'), ('CL', 'canceled')], default='TW', max_length=2, verbose_name='status')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('responsible', models.ManyToManyField(related_name='responsible', to=settings.AUTH_USER_MODEL, verbose_name='responsible')),
            ],
        ),
    ]
