# Generated by Django 3.2.5 on 2021-07-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='expiration_date',
            field=models.DateField(null=True, verbose_name='expiration date'),
        ),
    ]
